### PR TITLE
Add domain prefixed to username for Client#log_in method

### PR DESCRIPTION
**Pull request by beingben**

### CODE REVIEW

**Comment by zeljkofilipin** [comment]
Thanks for the pull request, but this is just a mirror. Please see this for instructions on how to contribute:

https://www.mediawiki.org/wiki/Developer_access

**Comment by beingben** [comment]
MediaWiki internal error.

Exception caught inside exception handler.

Set $wgShowExceptionDetails = true; at the bottom of LocalSettings.php to
show detailed debugging information.

**Comment by beingben** [comment]
Developer sign up is broken on the mediawiki site
MediaWiki internal error.

Exception caught inside exception handler.

Set $wgShowExceptionDetails = true; at the bottom of LocalSettings.php to show detailed debugging information.

**Comment by zeljkofilipin** [comment]
@beingben hm, it works for me :/

Can you try please again? Maybe it was down while you tried, but looks like it is fixed now.

**Pull request closed without merging**
