### PR TITLE
Add 'text' param to upload_image

### PR DESCRIPTION
**Pull request by abartov**
with a nil default so as not to break existing code

### CODE REVIEW

**Comment by zeljkofilipin** [comment]
Thanks for the contribution! This repository is just a mirror of the original one in Gerrit:

https://gerrit.wikimedia.org/r/#/admin/projects/mediawiki/ruby/api

Could you please send the patch there? (I will do it on Monday, if you do not do it by then.)

**Comment by zeljkofilipin** [comment]
Moved to gerrit: https://gerrit.wikimedia.org/r/#/c/334992/

**Comment by zeljkofilipin** [comment]
This is now merged into master. Should we release the new version of the gem? Or can this wait? We do not have any strict policy on when to release the gem.

**Comment by abartov** [comment]
I'd like to see this released as a new gem, yes.  It actually plugs a
not-insignificant weakness in upload_image: before it, the only way to make
the upload include licensing information, and author and description
templates, as e.g. Commons would expect, was to pass *all* of it in the
comment field.  Which is ugly and limited.

I would like to use this feature in a tool I maintain that relies on the
Ruby API[1], to resolve an open issue, so I'd welcome a release as a gem
soon.

Thanks,

  A.

[1] https://github.com/abartov/pronuncify

**Comment by zeljkofilipin** [comment]
Released: https://rubygems.org/gems/mediawiki_api

**Pull request closed without merging**
